apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-website
  namespace: ecommerce  # Add this line
  labels:
    app: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: prat2001/ecommerce-site:latest  # Use your correct Docker Hub username
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: ecommerce  # Add this line
spec:
  type: ClusterIP
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
